name: flutter_validation
description: Ready localized validation messages.
version: 1.0.8
homepage: https://github.com/OTF-7/flutter_validation

publish_to: "none"

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # validations
  phone_numbers_parser: ^9.0.3
  form_field_validator:
    git:
      url: https://github.com/OTF-7/form_field_validator.git
      ref: nested_multi_validator

  # localizations
  validation_localizations:
    git:
      url: https://github.com/OTF-7/flutter-localizations.git
      path: packages/validation_localizations
      ref: 1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
